python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name pytorch_resnet152_224px_pp0
python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name pytorch_resnet152_224px_pp1
python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name pytorch_resnet152_224px_pp2
python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name pytorch_resnet152_224px_pp3
python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name pytorch_resnet152_224px_pp4
python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name pytorch_resnet152_224px_RGB
python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name keras_ResNet152V2_224px_pp0
python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name keras_ResNet152V2_224px_pp1
python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name keras_ResNet152V2_224px_pp2
python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name keras_ResNet152V2_224px_pp3
python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name keras_ResNet152V2_224px_pp4
python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name keras_ResNet152V2_224px_RGB
python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name keras_ResNet152_224px_pp0
python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name keras_ResNet152_224px_pp1
python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name keras_ResNet152_224px_pp2
python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name keras_ResNet152_224px_pp3
python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name keras_ResNet152_224px_pp4
python ir_image_classification/svm_classification/svm_optimization.py --nworkers 11 --dataset_path datasets/extracted_datasets/ --dataset_name keras_ResNet152_224px_RGB
