#!/bin/bash

#SBATCH --time=45:55:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --mem=32GB
#SBATCH --job-name=ft_ships

ml TensorFlow/2.3.1-fosscuda-2019b-Python-3.7.4

source ../venv/bin/activate

python -u ir_image_classification/feature_extraction/keras/finetune_resnet_MARVEL.py
