#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64GB
#SBATCH --time=20:30:00
#SBATCH --partition=regular
#SBATCH --job-name=optimize_svm

ml TensorFlow/2.3.1-fosscuda-2019b-Python-3.7.4

source ../IR_venv/bin/activate

#python -u ir_image_classification/svm_classification/svm_optimization.py --dataset_path /home/s2576597/Pix2VoxPP/extracted_datasets --dataset_name side_other_view_early_features_ --nworkers 16
#python -u ir_image_classification/svm_classification/svm_optimization.py --dataset_path /home/s2576597/Pix2VoxPP/extracted_datasets --dataset_name side_other_view_early_features_ft_ --nworkers 16
#python -u ir_image_classification/svm_classification/svm_optimization.py --dataset_path /home/s2576597/Pix2VoxPP/extracted_datasets --dataset_name side_other_view_early_features_scratch_ --nworkers 16
#python -u ir_image_classification/svm_classification/svm_optimization.py --dataset_path /home/s2576597/Pix2VoxPP/extracted_datasets --dataset_name side_other_view_early_features_og_ --nworkers 16
#python -u ir_image_classification/svm_classification/svm_optimization.py --dataset_path /home/s2576597/Pix2VoxPP/extracted_datasets --dataset_name side_other_view_early_features_ft_centercrop_ --nworkers 16
#python -u ir_image_classification/svm_classification/svm_optimization.py --dataset_path /home/s2576597/Pix2VoxPP/extracted_datasets --dataset_name side_other_view_early_newds_ft_360_ --nworkers 16
#python -u ir_image_classification/svm_classification/svm_optimization.py --dataset_path /home/s2576597/Pix2VoxPP/extracted_datasets --dataset_name side_other_view_early_oldds_ft_goodcrop_ --nworkers 16
#python -u ir_image_classification/svm_classification/svm_optimization.py --dataset_path /home/s2576597/Pix2VoxPP/extracted_datasets --dataset_name side_other_view_early_newds_256_ft_300_ --nworkers 16
#python -u ir_image_classification/svm_classification/svm_optimization.py --dataset_path /home/s2576597/Pix2VoxPP/extracted_datasets --dataset_name side_other_view_early_newds_256_ft_300_new_dataloader_settings_ --nworkers 16
#python -u ir_image_classification/svm_classification/svm_optimization.py --dataset_path /home/s2576597/Pix2VoxPP/extracted_datasets --dataset_name side_other_view_early_newds_256_scratch_300_new_dataloader_settings_ --nworkers 16

#python -u ir_image_classification/svm_classification/svm_optimization.py --dataset_path /data/s2576597/extracted_datasets --dataset_name MARVEL_side_other_view_keras_ResNet152_224px --nworkers 16
#python -u ir_image_classification/svm_classification/svm_optimization.py --dataset_path /data/s2576597/extracted_datasets --dataset_name Resnet_and_Pix2Vox_combined --nworkers 16
python -u ir_image_classification/svm_classification/svm_optimization.py --dataset_path /data/s2576597/extracted_datasets --dataset_name Resnet_and_Pix2Vox_combined_normalized --nworkers 16
